# the defaults hyprland shipped with

# Create a smooth, water-like curve
bezier = waterFlow, 0.25, 1, 0.5, 1

animations {
    animation = windows,       1,     4.79,  easeOutQuint
    animation = windowsIn,     1,     4.1,   easeOutQuint, popin 87%
    animation = windowsOut,    1,     1.49,  linear,       popin 87%
    animation = fadeIn,        1,     1.73,  almostLinear
    animation = fadeOut,       1,     1.46,  almostLinear

}
