# the defaults hyprland shipped with

animations {
    animation = layers, 1, 3.81, easeOutQuint, fade
    animation = layersIn, 1, 4, easeOutQuint, fade
    animation = layersOut, 1, 1.5, linear, fade
    animation = fadeLayersIn, 1, 1.79, almostLinear
    animation = fadeLayersOut, 1, 1.39, almostLinear
}
