# Pyprland Dropdown Terminal Binds

# Alt + Space for index 0 dropdown terminal
bind = ALT, SPACE, exec, bash $pypr_script term_0

# Win + Alt + [0-9] keybindings for index 0..9 dropdown terminals
bind = $mainMod ALT, 0, exec, bash $pypr_script term_0
bind = $mainMod ALT, 1, exec, bash $pypr_script term_1
bind = $mainMod ALT, 2, exec, bash $pypr_script term_2
bind = $mainMod ALT, 3, exec, bash $pypr_script term_3
bind = $mainMod ALT, 4, exec, bash $pypr_script term_4
bind = $mainMod ALT, 5, exec, bash $pypr_script term_5
bind = $mainMod ALT, 6, exec, bash $pypr_script term_6
bind = $mainMod ALT, 7, exec, bash $pypr_script term_7
bind = $mainMod ALT, 8, exec, bash $pypr_script term_8
bind = $mainMod ALT, 9, exec, bash $pypr_script term_9

# Win + Alt + K to kill all pyprland dropdown terminals at once
bind = $mainMod ALT, K, exec, bash $pypr_script kill_all
