animations {
    # Default curves
    bezier = easeOutQuint,   0.23, 1,    0.32, 1
    bezier = easeInOutCubic, 0.65, 0.05, 0.36, 1
    bezier = linear,         0,    0,    1,    1
    bezier = almostLinear,   0.5,  0.5,  0.75, 1
    bezier = quick,          0.15, 0,    0.1,  1

    # New Preset Curves
    bezier = snappy,         0.05, 0.9,  0.1,  1.05
    bezier = bouncy,         0.175, 0.885, 0.32, 1.275
    bezier = smooth,         0.4,  0.0,  0.2,  1.0
}
