# ~/.config/hypr/configs/wallpaper.conf

#splash = false
#ipc = true
#
#wallpaper {
#    monitor = eDP-1
#    # Point this to the SYMLINK, not a specific image
#    path = $HOME/.config/hypr/scripts/wallpaper/selected-image
#    fit_mode = cover
#}
#
#wallpaper {
#    monitor =
#    path = $HOME/.config/hypr/scripts/wallpaper/selected-image
#    fit_mode = cover
#}

#wallpaper[]:path = $HOME/Pictures/wallpapers/Anime-City-Night.png
wallpaper[]:path = $HOME/Pictures/wallpapers/selected-image
splash = false
