#!/usr/bin/env bash
# v2_segment_5_pin_packages.sh
# Creates an APT preferences pin file for all packages
# resolved by v2_segment_2_resolve_deps.sh
# This prevents apt from upgrading them even when
# a newer version is available in Sid/unstable.

set -euo pipefail
INPUT_FILE="/tmp/hypr_target_deps.txt"
PIN_FILE="/etc/apt/preferences.d/hyprland-v2.pref"

C='\033[0;36m'; G='\033[0;32m'; Y='\033[1;33m'; B='\033[1m'; X='\033[0m'
info() { echo -e "${C}[INFO]${X} $*"; }
ok()   { echo -e "${G}[ OK ]${X} $*"; }

echo -e "${B}=================================================="
echo " STEP 5: Pin Packages via APT Preferences"
echo -e "==================================================${X}"

if [[ ! -f "$INPUT_FILE" ]]; then
  echo "Error: $INPUT_FILE not found. Run v2_segment_2_resolve_deps.sh first." >&2
  exit 1
fi

# Build the pin file content
PIN_CONTENT="# Hyprland ecosystem package pins\n"
PIN_CONTENT+="# Generated by v2_segment_5_pin_packages.sh\n"
PIN_CONTENT+="# Source: $INPUT_FILE\n\n"

while IFS='=' read -r pkg ver; do
  [[ "$pkg" =~ ^#.*$ || -z "$pkg" || -z "$ver" ]] && continue
  pkg="${pkg// /}"; ver="${ver// /}"

  PIN_CONTENT+="Package: $pkg\n"
  PIN_CONTENT+="Pin: version $ver\n"
  PIN_CONTENT+="Pin-Priority: 1001\n\n"
done < "$INPUT_FILE"

echo ""
info "Generated pin file contents:"
echo "=================================================="
echo -e "$PIN_CONTENT"
echo "=================================================="
echo ""
info "Writing to: $PIN_FILE"
echo -e "$PIN_CONTENT" | sudo tee "$PIN_FILE" > /dev/null
ok "Pin file written: $PIN_FILE"
echo ""
info "Verify with: apt-cache policy hyprland"
echo ""

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NEXT="$SCRIPT_DIR/v2_segment_6_hold_packages.sh"

read -p "Run next step (v2_segment_6_hold_packages.sh) to apply apt-mark hold? [Y/n]: " RUN_NEXT
RUN_NEXT="${RUN_NEXT:-Y}"
if [[ "$RUN_NEXT" =~ ^[Yy]$ ]]; then
  bash "$NEXT"
else
  echo "Skipped. Run manually:"
  echo "  $NEXT"
fi
