#!/usr/bin/env bash
# v2_segment_2_resolve_deps.sh
# Takes a Hyprland version, finds its snapshot timestamp,
# then resolves the matching versions of all ecosystem packages
# published at or before that timestamp.
# Output: /tmp/hypr_target_deps.txt (pkg=version pairs)

set -euo pipefail
SNAP="https://snapshot.debian.org"

C='\033[0;36m'; G='\033[0;32m'; Y='\033[1;33m'; R='\033[0;31m'; B='\033[1m'; X='\033[0m'
info() { echo -e "${C}[INFO]${X} $*"; }
ok()   { echo -e "${G}[ OK ]${X} $*"; }
warn() { echo -e "${Y}[WARN]${X} $*"; }
err()  { echo -e "${R}[ERR ]${X} $*" >&2; }

echo -e "${B}=================================================="
echo " STEP 2: Resolve Dependency Versions by Timestamp"
echo -e "==================================================${X}"

# Accept version as argument or read from previous script's output
TARGET_VER="${1:-}"
if [[ -z "$TARGET_VER" && -f /tmp/hypr_selected_version.txt ]]; then
  TARGET_VER=$(cat /tmp/hypr_selected_version.txt)
fi
if [[ -z "$TARGET_VER" ]]; then
  err "Usage: $0 <hyprland-version>"
  err "Or run v2_segment_1_search_versions.sh first."
  exit 1
fi

info "Target Hyprland version: $TARGET_VER"

# --- Step A: Get publication timestamp of target Hyprland version ---
info "Querying snapshot.debian.org for Hyprland $TARGET_VER..."
HASH=$(curl -sf "${SNAP}/mr/binary/hyprland/${TARGET_VER}/binfiles" \
  | python3 -c "import sys,json; d=json.load(sys.stdin); print([r for r in d['result'] if r.get('architecture')=='amd64'][0]['hash'])" 2>/dev/null \
  || curl -sf "${SNAP}/mr/binary/hyprland/${TARGET_VER}/binfiles" \
  | python3 -c "import sys,json; d=json.load(sys.stdin); print(d['result'][0]['hash'])" 2>/dev/null)

if [[ -z "$HASH" ]]; then
  err "Could not find Hyprland $TARGET_VER on snapshot.debian.org"
  exit 1
fi

TIMESTAMP=$(curl -sf "${SNAP}/mr/file/${HASH}/info" \
  | python3 -c "import sys,json; d=json.load(sys.stdin); print(d['result'][0]['first_seen'])" 2>/dev/null)

if [[ -z "$TIMESTAMP" ]]; then
  err "Could not resolve publication timestamp for Hyprland $TARGET_VER"
  exit 1
fi

ok "Hyprland $TARGET_VER was published at: $TIMESTAMP"

# --- Step B: Resolve ecosystem packages at that timestamp ---
ECOSYSTEM_PKGS=(
  hyprland
  hyprland-guiutils
  hyprlock
  hyprpaper
  xdg-desktop-portal-hyprland
  hyprcursor-util
  libaquamarine11
  libhyprcursor0
  libhyprgraphics4
  libhyprlang2
  libhyprtoolkit5
  libhyprutils12
  libhyprutils13
  libhyprutils-dev
  libhyprwire3
)

OUTPUT_FILE="/tmp/hypr_target_deps.txt"
echo "# Hyprland target: $TARGET_VER" > "$OUTPUT_FILE"
echo "# Resolved at snapshot timestamp: $TIMESTAMP" >> "$OUTPUT_FILE"
echo "# Generated by v2_segment_2_resolve_deps.sh" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

echo ""
printf "${B}%-35s %-35s${X}\n" "PACKAGE" "RESOLVED VERSION"
printf "%-35s %-35s\n"         "-------" "----------------"

for pkg in "${ECOSYSTEM_PKGS[@]}"; do
  # Get all versions of this package from snapshot
  VERSIONS_JSON=$(curl -sf "${SNAP}/mr/binary/${pkg}/" 2>/dev/null || true)
  if [[ -z "$VERSIONS_JSON" ]]; then
    warn "$pkg — could not query snapshot (skipping)"
    continue
  fi

  # Find the latest version whose first_seen <= TIMESTAMP
  MATCHED_VER=$(echo "$VERSIONS_JSON" | python3 -c "
import sys, json, urllib.request
data = json.load(sys.stdin)
snap = '${SNAP}'
ts_target = '${TIMESTAMP}'
pkg = '${pkg}'

for r in data.get('result', []):
    ver = r['binary_version']
    try:
        req = urllib.request.Request(
            f'{snap}/mr/binary/{pkg}/{ver}/binfiles',
            headers={'User-Agent': 'hypr-v2-resolver'}
        )
        b_data = json.loads(urllib.request.urlopen(req, timeout=10).read())
        results = b_data.get('result', [])
        amd64 = [x for x in results if x.get('architecture') == 'amd64']
        h = (amd64 or results)[0]['hash'] if (amd64 or results) else None
        if not h:
            continue
        req2 = urllib.request.Request(
            f'{snap}/mr/file/{h}/info',
            headers={'User-Agent': 'hypr-v2-resolver'}
        )
        i_data = json.loads(urllib.request.urlopen(req2, timeout=10).read())
        ts = i_data['result'][0]['first_seen']
        if ts <= ts_target:
            print(ver)
            break
    except Exception:
        continue
" 2>/dev/null || true)

  if [[ -n "$MATCHED_VER" ]]; then
    printf "%-35s ${G}%-35s${X}\n" "$pkg" "$MATCHED_VER"
    echo "${pkg}=${MATCHED_VER}" >> "$OUTPUT_FILE"
  else
    printf "%-35s ${Y}%-35s${X}\n" "$pkg" "NOT FOUND"
    warn "  $pkg — no matching version found at or before $TIMESTAMP"
  fi
done

echo ""
ok "Dependency map written to: $OUTPUT_FILE"
echo ""

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NEXT="$SCRIPT_DIR/v2_segment_3_download_debs.sh"

read -p "Run next step (v2_segment_3_download_debs.sh) to download all .deb files? [Y/n]: " RUN_NEXT
RUN_NEXT="${RUN_NEXT:-Y}"
if [[ "$RUN_NEXT" =~ ^[Yy]$ ]]; then
  bash "$NEXT"
else
  echo "Skipped. Run manually:"
  echo "  $NEXT"
fi
