###############################
### MY PROGRAMS & variables ###
###############################

# See https://wiki.hyprland.org/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$fileManager = thunar
$fileManager_alt = ranger
$menu = rofi -show drun
#$menu = wofi --show drun
$browser = $HOME/Applications/zen/zen
#$browser = microsoft-edge-stable


# On-demand scratchpad script location
$pypr_script = ~/.config/pypr/toggle_pypr.sh
