##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules
# Example windowrule v1
# windowrule = float, ^(kitty)$

# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$

#windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.
#
## Make yad float, centered, always on top
#windowrulev2 = float,class:^(yad)$
#windowrulev2 = center,class:^(yad)$
#windowrulev2 = stayfocused,class:^(yad)$
#windowrulev2 = pin,class:^(yad)$